### ISSUE TITLE
🤖 Initialize Repo

### ISSUE THREAD

**Issue by thekaushikls** [thekaushikls/Sage#1]
##  **GOAL**

Setup basic structure of the repo, to start migrating old notes.

## **SUBTASKS**
- [ ] 🚀 Setup Bug Report Template
- [ ] 🚀 Setup Feature Request Template
- [ ] 🚀 Setup Build Workflows
- [ ] 🚀 Setup Basic Google Analytics
- [ ] 🚀 Setup Minimal Website
