### ISSUE TITLE
🚀 Enable Comments

### ISSUE THREAD

**Issue by thekaushikls** [thekaushikls/Sage#2]
## DESCRIPTION

Enable a commenting system to allow potential feedback and criticism from readers.
[Giscuss](https://giscus.app/) can use GitHub Discussions as comment system.

---
<br>

## SUB-TASKS
- [x] 🚀 Enable comments only for select pages
- [x] 🚀 Comments are disabled by default
- [ ] ~~🚀 Anonymous comments for non-GitHub users~~

**Comment by thekaushikls** [comment]
Anonymous comments are hard to moderate.
